### ISSUE TITLE
Error running fold_feat_gen.py

### ISSUE THREAD

**Issue by aiXander** [IBM/fold2seq#1]
I'm getting errors running the preprocessing script:
```
total number of seqs: 470679
removed # seqs in ss.txt: 9337
Traceback (most recent call last):
  File "fold_feat_gen.py", line 154, in <module>
    x1,x2 = selection(line[0] ,  line[2], int(line[3]), int(line[4]), seq_ss)  
  File "fold_feat_gen.py", line 44, in selection
    start = start.replace(')','')
AttributeError: 'int' object has no attribute 'replace'
```

start and end are integers when I print them, so doesn't make sense that a string replace is applied to them... Any idea what's going on here?

**Comment by YueCao94** [comment]
We really thank you for your question! It is actually a bug in the code and we have fixed it.
