### ISSUE TITLE
where is domain_dict_full.pkl?

### ISSUE THREAD

**Issue by jkwang93** [IBM/fold2seq#5]
Good jobs. 
I try to run train.py, but can't find domain_dict_full.pkl. How can I get it?
Thanks~

**Comment by raiyan3** [comment]
Hi,

You'll have to construct the *.pkl files running the fold_feat_gen.py script. The *.pkl files are holding the residue information, later you'll need to run ss_dense_gen.py to create the feature files, these feature files (*.npy) will be used during training.

**Comment by jkwang93** [comment]
thanks very much~
